### ISSUE TITLE
Better way to make this exclusive to HTTPS

### ISSUE THREAD

**Issue by blyad2137** [FlashiFlasche/DuckDuckGo-Dark-Violet-Theme#1]
Instead of puting every link in the url-prefix just use a simple regexp line:
`regexp("^(https?)://duckduckgo.*`

**Comment by FulytheFox** [comment]
Hey, I think the problem with this is that every sub-site (like https://duckduckgo.com/app or https://duckduckgo.com/press) will be affected with the userstyle too.
Unfortunately I have so far only little experience with RegExp. Do you think there is any way to exclude such sites like that with this?

**Comment by blyad2137** [comment]
Put a string you want to exclude in here brackets like this: (?!).
Divide them by putting `|`.

Here's an actual example:
`@-moz-document regexp("^(https?)://duckduckgo.*(?!press|app)$^")`

**Comment by blyad2137** [comment]
duckduckgo.com: 
![image](https://user-images.githubusercontent.com/86572965/146402726-d51cc66c-f515-4348-914b-0f8788c4c754.png)

duckduckgo.com/app:
![image](https://user-images.githubusercontent.com/86572965/146402946-66b4eab3-d872-467f-83af-72f18ca74332.png)

**Comment by FlashiFlasche** [comment]
I understand your feedback, but that kinda breaks the whole theme. The theme should work on only these domains.
In a nutshell it should not change anything on the sites and the theme itself, so I really don't see the importance here.
